create comment:
AnnaKostyrko/chapter-backend pull request #71
Opened 2023-10-08 10:34 UTC by waridesu

- create controller, dto, module and service, length validation max 255

2023-10-08 19:46 UTC, AnnaKostyrko requested changes

2023-10-08 19:46 UTC, AnnaKostyrko commented on src/comment/comment.service.ts
> +  }
когда пишешь return - await уже не нужен

можно ли оптимизировать код вот так
async create(commentData: CreateCommentDto): Promise<CommentEntity> {
  return this.commentRepository.save(commentData);
}

2023-10-08 19:46 UTC, AnnaKostyrko commented on src/comment/dto/comment.dto.ts
> +  userId: number;
надо по красивому сделать)
чтобы ошибки возвращались везде
на число, на пустое значение, опциональное, написать экземплы в сваггер

2023-10-08 19:46 UTC, AnnaKostyrko commented on src/comment/comment.controller.ts
> +  @Post()
а почему юзер айди и пост айди передаются в бади, а не в пути?

2023-10-08 19:46 UTC, AnnaKostyrko commented on src/comment/comment.service.ts
> +    const comment = this.commentRepository.create(commentData);
как думаешь, стоит добавить проверку на то, существуют ли такой юзер и пост, которые придут с фронта?

2023-10-09 17:58 UTC, waridesu commented on src/comment/comment.service.ts
> +  }
done

2023-10-09 17:58 UTC, waridesu commented on src/comment/dto/comment.dto.ts
> +  userId: number;
done

2023-10-09 17:58 UTC, waridesu commented on src/comment/comment.controller.ts
> +  @Post()
done

2023-10-09 17:58 UTC, waridesu commented on src/comment/comment.service.ts
> +    const comment = this.commentRepository.create(commentData);
done

2023-10-10 15:01 UTC, merged