update comment:
AnnaKostyrko/chapter-backend pull request #72
Opened 2023-10-08 10:57 UTC by waridesu

- create controller, dto, module and service, length validation max 255

2023-10-08 19:58 UTC, AnnaKostyrko requested changes

2023-10-08 19:58 UTC, AnnaKostyrko commented on src/comment/comment.service.ts
> +  }
я не очень понимаю логику твою, может туплю, сорри

ты получается сначала обновляешь коммент в базе, потом ищешь его в базе и если нет, то ошибка и ретерн

а если сначала поискать такой коммент в базе и если нет, то ошибка. а если есть, то ретерн?

2023-10-08 19:58 UTC, AnnaKostyrko commented on src/comment/dto/comment.dto.ts
> +  text: string;
экзампел для сваггера давай добавим, пожалуйста

2023-10-08 19:58 UTC, AnnaKostyrko commented on src/comment/comment.controller.ts
> +  @Patch(':id')
я думаю, тут тоже можно commentId, а не айди
как минимум, чтобы в сваггере было понятно, что мы ждем

2023-10-09 17:58 UTC, waridesu commented on src/comment/comment.service.ts
> +  }
done

2023-10-09 17:58 UTC, waridesu commented on src/comment/dto/comment.dto.ts
> +  text: string;
done

2023-10-09 17:58 UTC, waridesu commented on src/comment/comment.controller.ts
> +  @Patch(':id')
done

2023-10-18 10:36 UTC, merged