like/unlike comment:
AnnaKostyrko/chapter-backend pull request #74
Opened 2023-10-08 11:47 UTC by waridesu

- update service, controller and module

2023-10-08 20:09 UTC, AnnaKostyrko requested changes

2023-10-08 20:09 UTC, AnnaKostyrko commented on src/like/like.service.ts
> +      return await this.getLikedUsers(commentId); // Предполагается, что у вас есть метод getLikedUsers для комментариев
мне непонятно, что ты этим комментом хотел сказать
метод либо есть либо надо его написать, если он нужен) ты о том, что его не нужно удалять, потому что без этого работать не будет?

2023-10-08 20:09 UTC, AnnaKostyrko commented on src/like/like.module.ts
> +    ]),
зачем тут прям все энтити импортированы?

2023-10-09 17:55 UTC, waridesu commented on src/like/like.module.ts
> +    ]),
![image](https://github.com/AnnaKostyrko/chapter-backend/assets/57594848/e1042be3-a540-45b4-b612-d941db80ee82)
уже были

2023-10-09 17:57 UTC, waridesu commented on src/like/like.service.ts
> +      return await this.getLikedUsers(commentId); // Предполагается, что у вас есть метод getLikedUsers для комментариев
done

2023-10-18 10:45 UTC, merged