fix/#178-Sign-up.-User-can-proceed-to-Create-account-page-after-entering-expired-confirmation-code-from-the-email
AnnaKostyrko/chapter-backend pull request #97
Opened 2023-11-02 18:39 UTC by innekto

fix hash exp

2023-11-02 19:26 UTC, AnnaKostyrko requested changes

2023-11-02 19:26 UTC, AnnaKostyrko commented on src/auth/auth.service.ts
> +      user.hash = null;
мы сохраняем дату создания хеша этого в базе?
если да, то проверяем дату при запросе и если время прошло - ошибка и хеш = null, если всё ок, то пропускаем

2023-11-05 10:34 UTC, innekto commented on src/auth/auth.service.ts
> +      user.hash = null;
у хеша немає дати

2023-11-06 08:36 UTC, AnnaKostyrko commented on src/auth/auth.service.ts
> +      user.hash = null;
updated at это не та дата, которая может нам подойти?

2023-11-06 08:38 UTC, innekto commented on src/auth/auth.service.ts
> +      user.hash = null;
может и подойти

2023-11-10 10:00 UTC, merged